#ifndef UI_MENU_H
#define UI_MENU_H
#include <Arduino.h>
#include "ui_icons_anim.h"

enum UiNodeType : uint8_t {
  NODE_SUBMENU, NODE_VALUE, NODE_TOGGLE, NODE_ACTION, NODE_INFO, NODE_STUB,
  NODE_DIAG, NODE_MONITOR, NODE_TUNE, NODE_TRIGGER,
  NODE_TRAIN_DRILL, NODE_TRAIN_FARNSWORTH, NODE_STATS,
  NODE_GAME_START, NODE_GAME_INFO, NODE_VOLUME,
  NODE_PROFILE_LOAD, NODE_PROFILE_SAVE, NODE_CALLSIGN_EDIT,
  NODE_TIMEOUT, NODE_CLOCK_EDIT
};

// Consumed only within ui_state.cpp/ui_backend.cpp - never crosses into
// core_trainer.h directly (ui_state.cpp's frozen no-core-includes rule).
// Positional mapping documented at ui_backend_trainStartSession().
enum UiTrainDrillId : uint8_t {
  TRAIN_DRILL_NONE = 0, TRAIN_DRILL_KOCH, TRAIN_DRILL_CHARACTERS,
  TRAIN_DRILL_WORDS, TRAIN_DRILL_CALLSIGNS, TRAIN_DRILL_ADAPTIVE, TRAIN_DRILL_EXAM
};

enum UiStatsId : uint8_t {
  STATS_NONE = 0, STATS_SESSION, STATS_LIFETIME, STATS_PROGRESS, STATS_ACCURACY, STATS_SPEED
};

enum UiProfileId : uint8_t { 
  UI_PROFILE_NONE = 0, UI_PROFILE_DEFAULT, UI_PROFILE_PORTABLE, 
  UI_PROFILE_CONTEST, UI_PROFILE_PRACTICE, UI_PROFILE_OUTDOOR, UI_PROFILE_SILENT
};

enum UiGameId : uint8_t { UI_GAME_NONE = 0, UI_GAME_COPY, UI_GAME_MEMORY, UI_GAME_SPEED };

enum UiParamId : uint8_t {
  PARAM_NONE = 0, PARAM_WPM, PARAM_TONE, PARAM_PADDLE_REV, PARAM_CONTRAST,
  PARAM_MODE, PARAM_DECODER_EN, PARAM_VOLUME, PARAM_SIDETONE_EN,
  PARAM_IAMBIC_MODE, PARAM_WEIGHT, PARAM_DISPLAY_INVERT, PARAM_CALLSIGN_EN
};

enum UiInfoId : uint8_t {
  INFO_NONE = 0, INFO_ABOUT, INFO_BLE_STATUS, INFO_SYSTEM_INFO,
  INFO_DEVICE_INFO, INFO_QUICK_START, INFO_CONTROLS, INFO_MORSE_GUIDE,
  INFO_BUTTON_GUIDE, INFO_GAMES_GUIDE,
  INFO_GAME_COPY_CONTROLS, INFO_GAME_COPY_HELP, INFO_GAME_COPY_SCORE,
  INFO_GAME_MEMORY_CONTROLS, INFO_GAME_MEMORY_HELP, INFO_GAME_MEMORY_SCORE,
  INFO_GAME_SPEED_CONTROLS, INFO_GAME_SPEED_HELP, INFO_GAME_SPEED_SCORE,
  INFO_PROFILE_DEFAULT, INFO_PROFILE_PORTABLE, INFO_PROFILE_CONTEST, INFO_PROFILE_PRACTICE,
  INFO_PROFILE_OUTDOOR, INFO_PROFILE_SILENT
};

enum UiDiagId : uint8_t {
  DIAG_NONE = 0, DIAG_INPUT, DIAG_DISPLAY, DIAG_AUDIO, DIAG_BLE,
  DIAG_GPIO, DIAG_SYSTEM, DIAG_MEMORY, DIAG_NVS, DIAG_HARDWARE
};

enum UiActionId : uint8_t {
  ACTION_NONE = 0, ACTION_BOND_RESET, ACTION_FACTORY_RESET, ACTION_RESTART,
  ACTION_PROFILE_SAVE
};

struct UiMenuNode {
  const char       *label;
  UiNodeType        type;
  const UiMenuNode *children;
  uint8_t           childCount;
  uint8_t           paramId;   // ParamId/InfoId/DiagId/ActionId, or for
                                // NODE_TRIGGER: memory slot index + 1
};

struct UiMainItem {
  const char       *title;
  const UiAnimIcon *icon;
  const UiMenuNode *children;
  uint8_t           childCount;
};

extern const UiMainItem UI_MAIN_MENU[];
extern const uint8_t    UI_MAIN_MENU_COUNT;

#endif